const Koa = require('koa')
const KoaBody = require('koa-body')
const userRouter = require('../router/user.route')
const errHandler = require('./errHandler')
const router = require('../router')
const app = new Koa()
app.use(KoaBody())
app.use(router.routes()).use(router.allowedMethods())
app.on('error', errHandler)
module.exports = app